USE PETCAREX
GO

-- SANPHAM
SELECT * FROM SANPHAM
SELECT * FROM VACCINE
SELECT * FROM THUOC
SELECT * FROM SANPHAMTONKHO

SELECT * FROM CHINHANH;

SELECT * FROM NHANVIEN
SELECT * FROM NVBACSI
SELECT * FROM NVBANHANG
SELECT * FROM NVTIEPTAN
SELECT * FROM NVQUANLY
SELECT * FROM LICHSUDIEUDONG

SELECT * FROM HOIVIEN
SELECT * FROM LICHSUCHITIEU

SELECT * FROM KHACHHANG
SELECT * FROM THUCUNG;

SELECT * FROM PHIEUDATLICH
SELECT * FROM HOSOBENHAN;
SELECT * FROM LICHSUTIEM

SELECT * FROM TOATHUOC
SELECT * FROM CHITIETTOATHUOC

SELECT * FROM GOITIEM
SELECT * FROM CHITIETGOITIEM

SELECT * FROM HOADON
SELECT * FROM CHITIETHOADON
SELECT * FROM CHITIETHOADON_BANLE
SELECT * FROM CHITIETHOADON_GOITIEM
SELECT * FROM CHITIETHOADON_KHAMBENH

SELECT * FROM PHIEUDANHGIA
SELECT * FROM DICHVU


USE PETCAREX; EXEC sp_spaceused;


SELECT COUNT(*) FROM HOADON

SELECT COUNT(*) FROM CHITIETHOADON;
SELECT * FROM CHITIETHOADON;

SELECT COUNT(*) FROM KHACHHANG

SELECT * FROM CHITIETGOITIEM

SELECT *
FROM HOSOBENHAN 
WHERE mathucung = 'TC2512101257289';


SELECT *
FROM CHITIETHOADON
WHERE giamoidonvi > 100000;