USE PETCAREX
GO

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET NOCOUNT ON;

-- Create index
IF NOT EXISTS (SELECT name FROM sys.indexes WHERE name = N'IX_THUCUNG_MaKhachHang')
BEGIN
    CREATE NONCLUSTERED INDEX IX_THUCUNG_MaKhachHang
    ON THUCUNG(makhachhang);
    
    PRINT 'Da tao index IX_THUCUNG_MaKhachHang';
END
GO

-- Clear cache
CHECKPOINT;
DBCC DROPCLEANBUFFERS; 
DBCC FREEPROCCACHE;    
GO

SET STATISTICS IO ON;   
SET STATISTICS TIME ON; 
SET STATISTICS PROFILE ON; 

PRINT '=== TEST 7: IX_THUCUNG_MaKhachHang - WITH INDEX ===';

-- Test query (sp_TraCuuThuCung_SDT)
SELECT * FROM THUCUNG TC
JOIN KHACHHANG KH ON TC.makhachhang = KH.makhachhang
WHERE KH.sodienthoai = '0936922252';

SET STATISTICS PROFILE OFF; 
SET STATISTICS TIME OFF; 
SET STATISTICS IO OFF; 
GO
