USE PETCAREX
GO

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET NOCOUNT ON;

-- Drop index if exists
IF EXISTS (SELECT name FROM sys.indexes WHERE name = N'IX_HOSOBENHAN_MaThuCung')
BEGIN
    DROP INDEX IX_HOSOBENHAN_MaThuCung ON HOSOBENHAN;
    PRINT 'Da xoa index IX_HOSOBENHAN_MaThuCung';
END 
GO

-- Clear cache
CHECKPOINT;
DBCC DROPCLEANBUFFERS; 
DBCC FREEPROCCACHE;    
GO

SET STATISTICS IO ON;   
SET STATISTICS TIME ON; 
SET STATISTICS PROFILE ON; 

PRINT '=== TEST 8: IX_HOSOBENHAN_MaThuCung - WITHOUT INDEX ===';

-- Test query (sp_TraCuuHosoBenhAn)
SELECT TOP 10 * FROM HOSOBENHAN 
WHERE mathucung = 'TC2512211735000' 
ORDER BY ngaykham DESC;

SET STATISTICS PROFILE OFF; 
SET STATISTICS TIME OFF; 
SET STATISTICS IO OFF; 
GO
