USE PETCAREX
GO

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET NOCOUNT ON;

-- Create index
IF NOT EXISTS (SELECT name FROM sys.indexes WHERE name = N'IX_HOSOBENHAN_MaThuCung')
BEGIN
    CREATE NONCLUSTERED INDEX IX_HOSOBENHAN_MaThuCung
    ON HOSOBENHAN(mathucung)
    INCLUDE (ngaykham, chuandoan);
    
    PRINT 'Da tao index IX_HOSOBENHAN_MaThuCung';
END
GO

-- Clear cache
CHECKPOINT;
DBCC DROPCLEANBUFFERS; 
DBCC FREEPROCCACHE;    
GO

SET STATISTICS IO ON;   
SET STATISTICS TIME ON; 
SET STATISTICS PROFILE ON; 

PRINT '=== TEST 8: IX_HOSOBENHAN_MaThuCung - WITH INDEX ===';

-- Test query (sp_TraCuuHosoBenhAn)
SELECT TOP 10 * FROM HOSOBENHAN 
WHERE mathucung = 'TC2512211735000' 
ORDER BY ngaykham DESC;

SET STATISTICS PROFILE OFF; 
SET STATISTICS TIME OFF; 
SET STATISTICS IO OFF; 
GO
